### ISSUE TITLE
undefined method `name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by studgeek** [wsargent/toodledo#12]
This error just started in the last few days. I have tried a fresh install. I'm wondering if toodledo API has changed  bit.

```
$ toodledo add 'test'
/Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/lib/toodledo/session.rb:248:in `call': undefined method `name' for nil:NilClass (NoMethodError)
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/lib/toodledo/session.rb:343:in `get_uncached_token'
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/lib/toodledo/session.rb:278:in `get_token'
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/lib/toodledo/session.rb:99:in `connect'
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/lib/toodledo.rb:59:in `begin'
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/lib/toodledo/command_line/add_command.rb:117:in `execute'
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/cmdparse-2.0.6/lib/cmdparse.rb:464:in `parse'
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/lib/toodledo/command_line/client.rb:920:in `main'
	from /Users/drxxx/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/toodledo-1.4.2/bin/toodledo:11:in `<top (required)>'
	from /Users/drxxx/.rbenv/versions/2.4.2/bin/toodledo:23:in `load'
	from /Users/drxxx/.rbenv/versions/2.4.2/bin/toodledo:23:in `<main>'

```

**Comment by alswl** [comment]
#8
