### ISSUE TITLE
Issue with setup

### ISSUE THREAD

**Issue by moshner** [wsargent/toodledo#8]
I am a pro account holder and tried to setup my account using toodledo setup. For some reason it wouldn't work and is giving me this error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse': (<unknown>): could not find expected ':' while scanning a simple key at line 17 column 3 (Psych::SyntaxError)
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:205:in `parse_stream'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:153:in `parse'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/psych.rb:129:in `load'
    from /Library/Ruby/Gems/2.0.0/gems/toodledo-1.4.1/lib/toodledo/command_line/client.rb:74:in `initialize'
    from /Library/Ruby/Gems/2.0.0/gems/toodledo-1.4.1/bin/toodledo:10:in `new'
    from /Library/Ruby/Gems/2.0.0/gems/toodledo-1.4.1/bin/toodledo:10:in `<top (required)>'
    from /usr/bin/toodledo:23:in `load'
    from /usr/bin/toodledo:23:in `<main>'
```

**Comment by drneill** [comment]
Same issue for me.

**Comment by wsargent** [comment]
Okay, something's up with your YAML file.  Did you enter in your password?

**Comment by nicechang** [comment]
I have the same problem.

**Comment by wsargent** [comment]
Okay... well, I'm absolutely out of time and don't have a development environment on me.  If someone can submit a pull request, I'll review it and send it in...

**Comment by alswl** [comment]
@wsargent It's a simple question, replace "http://www.toodledo.com/api.php" with "https://www.toodledo.com/api.php" in `~/.toodledo/user-config.yml`.
